"""create MovieVector table

Revision ID: 9c6bdcd74f3c
Revises: 9f3d56275096
Create Date: 2024-09-16 02:02:02.154828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6bdcd74f3c'
down_revision = '9f3d56275096'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_vector',
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('vector', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_index(op.f('ix_movie_vector_movie_id'), 'movie_vector', ['movie_id'], unique=False)
    op.drop_index('ix_movie_id', table_name='movie')
    op.create_index(op.f('ix_movie_movie_id'), 'movie', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_movie_id'), table_name='movie')
    op.create_index('ix_movie_id', 'movie', ['movie_id'], unique=False)
    op.drop_index(op.f('ix_movie_vector_movie_id'), table_name='movie_vector')
    op.drop_table('movie_vector')
    # ### end Alembic commands ###
