"""add movie table

Revision ID: 9f3d56275096
Revises: 2dd800eb3ad7
Create Date: 2024-09-09 21:55:13.983436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9f3d56275096"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie",
        sa.Column("movie_id", sa.Uuid(), nullable=False),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.Column("director", sa.String(), nullable=True),
        sa.Column("cast", sa.String(), nullable=True),
        sa.Column("genre", sa.String(), nullable=True),
        sa.Column("wiki_page", sa.String(), nullable=True),
        sa.Column("plot", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("movie_id"),
    )
    op.create_index(op.f("ix_movie_id"), "movie", ["movie_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movie_id"), table_name="movie")
    op.drop_table("movie")
    # ### end Alembic commands ###
